server.port=5000
server.servlet.context-path=/
server.address=0.0.0.0
spring.application.name=nutrition-api
spring.profiles.active=dev


spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.connection.autocommit=false
spring.jpa.properties.hibernate.transaction.flush_before_completion=true
spring.jpa.properties.hibernate.transaction.auto_close_session=false

ai.provider=spring
ai.openrouter.api-key=${AI_OPENROUTER_KEY}
ai.openrouter.base-url=https://openrouter.ai/api/v1
ai.openrouter.model=deepseek/deepseek-r1:free


jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME}   # ej: mottinutsoporte@gmail.com
spring.mail.password=${EMAIL_PASSWORD}   # app password Gmail
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

twilio.account-sid=${TWILIO_ACCOUNT_SID}
twilio.auth-token=${TWILIO_AUTH_TOKEN}
twilio.phone-number=${TWILIO_PHONE_NUMBER}
twilio.whatsapp-number=${TWILIO_WHATSAPP_NUMBER}


firebase.credentials-json-base64=${FIREBASE_CREDENTIALS_BASE64}

verification.code.expiration-minutes=10
verification.email.from=noreply@mottinut.com
verification.email.company-name=MottiNut

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

notification.retry.max-attempts=3
notification.retry.delay-minutes=5
notification.cleanup.retention-days=30

spring.task.scheduling.enabled=true
spring.task.scheduling.pool.size=2
